### ISSUE TITLE
Interactive `push` command can't be run without interactivity

### ISSUE THREAD

**Issue by ylv-io** [zeppelinos/zos#872] opened 2019-05-16 10:33 UTC
If you have Solidity contracts which are not `added` to a project then a `push` command like `zos push --network development` would ask you which contracts you want to `add/push`.
There is no `--all` flag so it is no possible to `push` without input unless you specify `--no-interactive`.
Also this happens only if you have no contracts in your `zos.json`. If you have at least one contract you'll be not asked to add any. Is this by design?
I am not sure is it by design or not. I belive commands should have sufficient arguments/options available so no input required.

**Comment by spalladino** [comment] 2019-05-16 18:17
Agree on this one. As a general rule, I'd say that if a user runs a command in 2.3 with exactly the same arguments as in 2.2, it should just run and not prompt any questions to the user. As for push in particular, ideally a standard interactive user should never need to invoke it directly, as it should be called behind the scenes on every create and update.

@jcarpanelli I want to hear your thoughts about this one!

**Comment by ylv-io** [comment] 2019-05-16 18:53
It seem we are going to break backwards compatibility here, right?

**Comment by jcarpanelli** [comment] 2019-05-17 19:58
> I am not sure is it by design or not. I belive commands should have sufficient arguments/options available so no input required.

Yes, it's by design. As we chatted offline, the idea behind this is to have a convention over configuration tool so users don't have to run unnecessary commands and get frustrated by avoidable (and awful) errors.

> I'd say that if a user runs a command in 2.3 with exactly the same arguments as in 2.2, it should just run and not prompt any questions to the user. As for push in particular, ideally a standard interactive user should never need to invoke it directly, as it should be called behind the scenes on every create and update.

I slightly agree on this, but just because we shouldn't break backwards compatibility.  I'm afraid that we will be breaking backwards compatibility also in the `create` and `update` commands as well, as those commands are calling the `add` and `push` commands. 
IMHO we shouldn't concern that much about breaking compatibility, as long as we provide a flag or an option to reproduce exactly the same scenario in `v2.3` as in `v2.2`. That being said, we can whether remove this feature for now (and add it again for the next major release) or provide a `--skip-precedent-commands` (or something similar) and properly communicate it.

**Comment by spalladino** [comment] 2019-05-17 20:14
> I'm afraid that we will be breaking backwards compatibility on the create and update commands as well, as those commands are calling the add and push commands.

Assuming the user runs `zos add MyContract`, `zos push`, and then `zos create MyContract --network local` - would they still get a prompt from `zos create`?

**Comment by spalladino** [comment] 2019-05-17 20:29
Sorry, I had misunderstood the original issue. As both of you mentioned and I inexcusably missed, the prompt only happens _when there are no contracts_ added to `zos.json`, and not on every `push`. 

So we would be breaking backwards compatibility only for scripts that were not correct in the first place (since they were running push before running add), which is something I'm fine with. The way for `push` not to prompt (without relying on `--no-interactive`) is to call it after an `add`. 

With that in mind, I'd close this issue. @ylv-io is that ok for you?

**Comment by ylv-io** [comment] 2019-05-19 10:59
yes, I am totally okay with closing this issue!

**Comment by spalladino** [comment] 2019-05-20 13:23
Cool, closing then! Thanks to you both!

**Closed by spalladino** 2019-05-20 13:23 UTC
Labels: component:cli, kind:bug, kind:discussion
