### ISSUE TITLE
Upgrade tutorial with new public state variable doesn't create zero parameter getter

### ISSUE THREAD

**Issue by abcoathup** [zeppelinos/zos#906] opened 2019-05-23 00:26 UTC
Following ZeppelinOS tutorial https://docs.zeppelinos.org/docs/upgrading.html when adding a new public state variable and then accessing via truffle console results in `Error: Invalid number of parameters for "t". Got 0 expected 2!` when calling `(await mc.t()).toString()`.  

Versions
`npx zos --version` 2.2.3
`npx truffle version` Truffle v5.0.18 (core: 5.0.18)
`npx ganache-cli` Ganache CLI v6.4.3 (ganache-core: 2.5.5)

Running `console.log(mc.methods)` shows `'t(uint256,string)'` and doesn’t include a method for `'t()'`

Discussion in the forum
https://forum.zeppelin.solutions/t/problem-adding-new-initialize-function-to-upgradeable-contract-tutorial/705/5

Tutorial works with:
`npx zos --version` 2.2.3
`npx truffle version` Truffle v5.0.2 (core: 5.0.2)
`npx ganache-cli` Ganache CLI v6.3.0 (ganache-core: 2.4.0)

**Comment by spalladino** [comment] 2019-05-23 23:23
This seems to be an issue with Truffle, as I've reproduced it in a sample project without zOS. I have filed [this issue](https://github.com/trufflesuite/truffle/issues/2048) on their tracker.

**Comment by abcoathup** [comment] 2019-05-23 23:37
The [first part of the tutorial](https://docs.zeppelinos.org/docs/deploying) clearly states a working version of truffle to use.  (I of course used the latest version) :smiley:
```
npm install truffle@5.0.4
```

**Comment by spalladino** [comment] 2019-05-24 14:30
Closing the issue then!

**Closed by spalladino** 2019-05-24 14:30 UTC

**Comment by abcoathup** [comment] 2019-05-31 04:42
Issue https://github.com/trufflesuite/truffle/issues/2048 fixed in [Truffle v5.0.20](https://github.com/trufflesuite/truffle/releases/tag/v5.0.20)

Reran tutorial with Truffle 5.0.20 successfully
