### ISSUE TITLE
Decide where Initializable should be placed

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos#143] opened 2018-09-28 15:16 UTC
We've been thinking about moving `Initializable` from `zos-lib` to [openzeppelin-zos](https://github.com/OpenZeppelin/openzeppelin-zos) since it is needed to make every provided contract upgradeable. 

However, this means that every user willing to use `zos` to build an upgradeable application will have to install `openzeppelin-zos` as well. Then, they will be importing a whole library to use a single contract. This could be seen as a way to motivate users to use `openzeppelin-zos` for their projects too. But they may end extending from those contracts instead of using them on-chain tho.

Another option could be to move `Initializable` to a third repository shared between `openzeppelin-zos` and `zos`

**Comment by facuspagnuolo** [comment] 2018-09-28 15:18
We may want to consider that vouching and TPL also depend on this

**Comment by maraoz** [comment] 2018-10-01 21:19
@facuspagnuolo as I told you offline, I don't like the idea of `Initializable` being in `openzeppelin-zos`. Just making my opinion public here.

**Comment by frangio** [comment] 2018-10-01 21:43
I don't think the problem is circular references. The main problem is that Truffle does not understand nested dependencies and this results in a bad user experience. What I mean is that if `openzeppelin-zos` contracts have an `import 'zos-lib/...'` statement (or whatever other package), Truffle will not resolve the import to `openzeppelin-zos`'s `zos-lib` dependency but to the `zos-lib` that is installed in the user's project. So we have to tell users to install `openzeppelin-zos` and `zos-lib` side-by-side. This can be hinted at by defining a `peerDependency` (what we do now) but the user still has to manually install it.

Having `Initializable` in `openzeppelin-zos` works around the problem but is definitely not a good long-term solution.

I'm okay with keeping `Initializable` in `zos-lib`.

**Comment by frangio** [comment] 2018-10-01 21:44
@spalladino Could you explain the circular dependencies problem a bit further?

**Comment by spalladino** [comment] 2018-10-01 21:58
@frangio I was thinking about zos-lib depending on oz-zos for using RBAC (or other mixin), and oz-zos depending on zos-lib for Initializable.

However, you make a good point about nested dependencies. With that in mind, maybe the best option would be to actually duplicate the Initializable contract for the time being in both repos. WDYT?

**Comment by frangio** [comment] 2018-10-02 02:14
That works for me. Note that the `initializer` modifier also would need to have an obscured name, in case the user wants to extend an `oz-zos` contract and add custom initialization logic using `zos-lib` `Initializable`. I'll think about this a bit more tomorrow but I don't think there would be any further problems in that scenario.

It's somewhat interesting that `oz-zos` having its own `Initializable` sort of reinforces the idea that you don't _need_ to use `zos-lib` `Initializable`, it is only a utility but you can implement similar behavior in other ways.

**Comment by spalladino** [comment] 2018-10-02 13:10
Now that I think of it: wouldn't having both Initializable contracts in a
single project open the door to double-initializations? Suppose I extend
from oz-zos/ERC20, and also from zos-lib/Initializable as the tutorials
recommend me to do. Then my contract may end up having two initializers,
one from each Initializable implementation, and one would probably be left
open for an attacker to call, right? Or this would not be an issue, as only
one Initializable would actually be used for setting up the contract?

**Comment by alcuadrado** [comment] 2018-10-02 14:18
@spalladino I've been thinking about that too. 

My understanding is that modifiers inherited multiple times (`initializer` in this case) behave like functions inherited multiple times, and only the most-derived one is used. This translates in every contract checking the same `initialized` and `initializing` variables, making `initializer` safe. But AFAIK this is undocumented behavior in `solc`. I'm pretty sure that `Initializable`'s storage is reserved twice though.

Note that to inherit bot `Initializable`s one has to be imported with an alias or the compilation process will fail.

**Comment by spalladino** [comment] 2018-10-02 15:54
> Note that to inherit bot Initializables one has to be imported with an
alias or the compilation process will fail.

Yes, I was thinking about the case in which Initializable was renamed in
oz-zos.

**Comment by spalladino** [comment] 2018-10-02 20:30
After all the discussion, I've come to the opinion that the safest option is to keep a single Initializable in `zos-lib`, and make it a peerDependency of `oz-zos` as @frangio mentioned, even if it's not the best UX. WDYT?

**Comment by facuspagnuolo** [comment] 2018-10-02 20:48
Agree, let's go with it. Could you add some details to this issue with the next steps to solve it?

**Comment by frangio** [comment] 2018-10-02 21:09
>wouldn't having both Initializable contracts in a single project open the door to double-initializations?

I'm not sure I understand this. In the scenario you described, if the user extends `ERC20` they _have to_ call `ERC20.initialize()` in their custom initialization logic. This should prevent any future calls of `initialize`. An attacker would be able to invoke `ERC20.initialize` externally only if the user doesn't invoke it themselves, in which case they'd have an uninitialized contract so wouldn't this situation be evident?

**Comment by spalladino** [comment] 2018-10-02 22:33
> I'm not sure I understand this. In the scenario you described, if the user extends ERC20 they have to call ERC20.initialize() in their custom initialization logic. This should prevent any future calls of initialize. An attacker would be able to invoke ERC20.initialize externally only if the user doesn't invoke it themselves, in which case they'd have an uninitialized contract so wouldn't this situation be evident?

My concern is precisely if they forget to call `ERC20.initialize()` in the user contract initializer. In that case, only the `ERC20` part of the contract would be left uninitialized, as the user will happily create a proxy and initialize it, without noticing that a different initializer was left out. The problem is that an attacker can still initialize that part afterwards.

If both the child and ERC20 share the same initializer, and the user forgets to call `ERC20.initialize()` from the user contract initializer, then the ERC20 part is also left uninitialized, but no one can initialize it afterwards.

**Comment by spalladino** [comment] 2018-10-03 16:10
Discussed offline with @frangio. We agreed on avoiding the chance of having two different `isInitialized` flags on the same contract, so we'll keep a single `Initializable` implementation on `zos-lib`, and declare it as a peer dependency of `oz-zos`. We may want to explore explicitly installing `zos-lib` as part of `zos init` to support this more easily.

Also, note that the `Initializable` from oz-zos has a small change, so we'll need to update `zos-lib` to reflect that change.

**Comment by nventuro** [comment] 2018-10-10 15:54
Closed via https://github.com/OpenZeppelin/openzeppelin-zos/pull/31 and https://github.com/zeppelinos/zos/pull/215.

**Closed by nventuro** 2018-10-10 15:54 UTC
Labels: component:contracts, kind:discussion
