### ISSUE TITLE
zos push fails on solidity warnings (e.g., with ABIEncoderV2)

### ISSUE THREAD

**Issue by snario** [zeppelinos/zos#369] opened 2018-10-26 01:10 UTC
I was trying to play around with `zos` and noticed the `zos push` command will fail on warnings, for example:

```shell
Example.sol:2:1: Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental "ABIEncoderV2";
^---------------------------------^
```

I thought perhaps the `--force` option would help but it did not

**Comment by spalladino** [comment] 2018-10-26 09:46
Hey @snario, thanks for the report! I'm afraid I'm not being able to reproduce it:
```bash
~/Projects/zeppelinos/zos-workshop (master)$ zos push --network local
Compiling contracts
(...)

Compilation warnings encountered:

/home/spalladino/Projects/zeppelinos/zos-workshop/contracts/solutions/UpgradeableWallet.sol:2:1: Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental "ABIEncoderV2";
^---------------------------------^

Writing artifacts to ./build/contracts

Validating contract UpgradeableWallet
Uploading UpgradeableWallet contract as Wallet
Deploying logic contract for UpgradeableWallet
Created zos.dev-8888.json
~/Projects/zeppelinos/zos-workshop (master)$ zos --version
2.0.0
```

Is there any chance there are other issues on the compilation? Mind sharing your contract code, or the full output from the `zos push command`? Thanks!

**Comment by facuspagnuolo** [comment] 2018-11-26 10:39
Closing this issue since there was no answer in the last 30 days.

**Closed by facuspagnuolo** 2018-11-26 10:39 UTC
Labels: kind:bug, status:more-info-required
