### ISSUE TITLE
zos compile - Invalid URI

### ISSUE THREAD

**Issue by creazy231** [zeppelinos/zos#1049] opened 2019-06-26 11:19 UTC
I was following the **Your first project**-Tutorial and have the following error:
```
λ zos compile
Invalid URI "c:/Users/Tobias/Documents/PROJEKTE/Contracts/zos-test/contracts/Counter.sol"
```

**Comment by ylv-io** [comment] 2019-06-26 11:22
Hey @creazy231!
Would you mind to share which version of zos you are using? Run `zos --version`.

**Comment by creazy231** [comment] 2019-06-26 11:37
Using 2.4.0

**Comment by creazy231** [comment] 2019-06-26 12:51
FYI: Using newest windows 10.

**Comment by jcarpanelli** [comment] 2019-06-26 14:19
Hey @creazy231, one more favor! could you please rerun the `zos compile` using the `--verbose` flag (`zos compile --verbose`) and share the output here? Thanks!

**Comment by creazy231** [comment] 2019-06-26 14:31
@jcarpanelli 
```
λ zos compile --verbose
[2019-06-26T14:30:25.057Z@ErrorHandler.js#call] <started> Error: Invalid URI "c:/Users/Tobias/Documents/PROJEKTE/Contracts/zos-test/contracts/Counter.sol"
    at Request.init (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\request\request.js:273:31)
    at new Request (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\request\request.js:127:8)
    at Object.request [as default] (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\request\index.js:53:10)
    at Promise (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\parsers\urlparser.js:18:26)
    at new Promise (<anonymous>)
    at UrlParser (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\parsers\urlparser.js:10:21)
    at core_1.firstResult.parser (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\imports\build\parsers\importparser.js:19:74)
    at Object.<anonymous> (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\utils.js:14:34)
    at Generator.next (<anonymous>)
    at C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\utils.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\utils.js:3:12)
    at Object.firstResult (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\utils.js:12:12)
    at Object.<anonymous> (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\imports\build\parsers\importparser.js:19:37)
    at Generator.next (<anonymous>)
    at C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\imports\build\parsers\importparser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\imports\build\parsers\importparser.js:3:12)
    at ImportParser (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\imports\build\parsers\importparser.js:18:26)
    at utils_1.firstResult.parser (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\resolverengine.js:58:78)
    at Object.<anonymous> (C:\Users\Tobias\Documents\PROJEKTE\Contracts\zos-test\node_modules\@resolver-engine\core\build\utils.js:14:34)
    at Generator.next (<anonymous>)
```

**Comment by spalladino** [comment] 2019-06-28 21:29
Hey @creazy231! This is caused by an issue in one of our dependencies (see https://github.com/Crypto-Punkers/resolver-engine/issues/182). We'll see if it can be fixed there and update, or try to monkey-patch it on our side if not possible

**Comment by jcarpanelli** [comment] 2019-07-11 14:57
Fixed in https://github.com/zeppelinos/zos/pull/1066.

**Closed by jcarpanelli** 2019-07-11 14:57 UTC
Labels: component:compiler, kind:bug
